In [3]:
x={'name':{'a':1,'b':2},'class':23}

x.values()

dict_values([{'a': 1, 'b': 2}, 23])

In [120]:
# creating new hospital 
from pydantic import BaseModel , EmailStr

In [7]:
class Hospital(BaseModel):
    name: str
    reg_id: int
    phone : int
    email : EmailStr
    place : str

In [22]:
nisar = Hospital(name='nisar hospital',reg_id='1423232',phone=99952324,email='asd@gmail.com',place='valy')

In [23]:
type(nisar.reg_id)

int

In [37]:
temp={}
for i in nisar:
    temp[i[0]]=i[1]

In [38]:
temp

{'name': 'nisar hospital',
 'reg_id': 1423232,
 'phone': 99952324,
 'email': 'asd@gmail.com',
 'place': 'valy'}

In [8]:
import pandas as pd


In [45]:
df = pd.Series(temp)

In [49]:
df2 = pd.Series(temp)

In [51]:
df = pd.DataFrame(data=[temp])

In [52]:
df

name   reg_id     phone          email place
0  nisar hospital  1423232  99952324  asd@gmail.com  valy

In [53]:
df3 = pd.DataFrame([temp])

In [54]:
df3

name   reg_id     phone          email place
0  nisar hospital  1423232  99952324  asd@gmail.com  valy

In [57]:
pd.concat([df3,df],ignore_index=True)

name   reg_id     phone          email place
0  nisar hospital  1423232  99952324  asd@gmail.com  valy
1  nisar hospital  1423232  99952324  asd@gmail.com  valy

In [58]:
df3

name   reg_id     phone          email place
0  nisar hospital  1423232  99952324  asd@gmail.com  valy

AttributeError: 'DataFrame' object has no attribute 'append'

In [48]:
df.shape

(5,)

In [43]:
df

name   reg_id     phone          email place
1  nisar hospital  1423232  99952324  asd@gmail.com  valy
2  nisar hospital  1423232  99952324  asd@gmail.com  valy
3  nisar hospital  1423232  99952324  asd@gmail.com  valy
4  nisar hospital  1423232  99952324  asd@gmail.com  valy

In [3]:
1/-25


-0.04

In [12]:
import db

In [21]:
df = pd.read_csv('/home/abdurahiman/Desktop/fastapi_tut/db.csv')

In [22]:
df

Empty DataFrame
Columns: [1, 2, 3]
Index: []

In [13]:
dt = {1:'as',2:'sd',3:'xs'}

In [24]:
dt = pd.DataFrame([dt])

In [25]:
dt

1   2   3
0  as  sd  xs

In [26]:
df

Empty DataFrame
Columns: [1, 2, 3]
Index: []

In [36]:
pd.concat([df,dt],ignore_index=True,axis=0)

1    2    3   1   2   3
0  NaN  NaN  NaN  as  sd  xs

In [29]:
df

Empty DataFrame
Columns: [1, 2, 3]
Index: []

In [31]:
df[1]

KeyError: 1

In [33]:
df.shape

(0, 3)

In [34]:
df.columns

Index(['1', '2', '3'], dtype='object')

In [37]:
df

Empty DataFrame
Columns: [1, 2, 3]
Index: []

In [42]:
df['1'][0]='new'

/tmp/ipykernel_5719/1565001520.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['1'][0]='new'


In [43]:
df

Empty DataFrame
Columns: [1, 2, 3, 1]
Index: []

In [47]:
df.drop(1,axis=1,inplace=True)

In [50]:
df.iloc[0]=['sd','df','gd']

IndexError: iloc cannot enlarge its target object

In [139]:
db =pd.read_csv('db.csv')

In [116]:
db

Empty DataFrame
Columns: [name, reg_id, phone, email, place]
Index: []

In [118]:
db.loc[len(db)]=[1,2,3,4,5]

In [119]:
db

name  reg_id  phone  email  place
0     1       2      3      4      5

In [121]:
class Hospital(BaseModel):
    name: str
    reg_id: int
    phone : int
    email : EmailStr
    place : str

In [123]:
name1 = Hospital(name='a',reg_id=23,phone=34,email='a@gmail.com',place='vly')

In [124]:
name1

Hospital(name='a', reg_id=23, phone=34, email='a@gmail.com', place='vly')

In [127]:
v=name1.model_dump_json()

In [132]:
v

'{"name":"a","reg_id":23,"phone":34,"email":"a@gmail.com","place":"vly"}'

In [133]:
c=name1.model_dump()

In [159]:
c

{'name': 'a',
 'reg_id': 23,
 'phone': 34,
 'email': 'a@gmail.com',
 'place': 'vly'}

In [136]:
temp = pd.DataFrame([c])

In [137]:
temp

name  reg_id  phone        email place
0    a      23     34  a@gmail.com   vly

In [140]:
db

Empty DataFrame
Columns: [name, reg_id, phone, email, place]
Index: []

In [149]:
db = pd.concat([db,temp],ignore_index=True)

In [150]:
db

name reg_id phone        email place
0    a     23    34  a@gmail.com   vly
1    a     23    34  a@gmail.com   vly
2    a     23    34  a@gmail.com   vly
3    a     23    34  a@gmail.com   vly
4    a     23    34  a@gmail.com   vly

In [162]:
db =  pd.read_csv('db/db.csv')

In [163]:
db

name  reg_id   phone            email place
0  nisar    1234  123456  nsr@example.com   vly

In [20]:
from fastapi import FastAPI
from pydantic import BaseModel,EmailStr,PositiveInt,NegativeInt


In [5]:
app = FastAPI()

In [6]:
class Hospital(BaseModel):
    name: str
    reg_id: int
    phone : int
    email : EmailStr
    place : str

In [7]:
@app.post('/add_details')
async def register(val:Hospital):
    db=pd.read_csv('db/db.csv')
    # js_compatible = jsonable_encoder(val)
    data = val.model_dump()
    temp = pd.DataFrame([data])
    db = pd.concat([db,temp],ignore_index=True)
    db.to_csv('db/db.csv',index=False)

    return{'message':db}  

In [8]:
det = Hospital(name='asd',reg_id=123,phone=123,email='q@gmail.com',place='df')

In [10]:
x=register(det)

In [16]:
x.cr_code

<code object register at 0x729607fc0200, file "/tmp/ipykernel_9669/3612143552.py", line 1>

In [12]:
import pandas as pd

In [19]:
pd.read_csv('db/db.csv')

name  reg_id   phone             email    place
0   nisar    1234  123456   nsr@example.com      vly
1     nis  234234    2345    ns@example.com      vly
2      as     123     344    ab@example.com      acv
3  string       0       0  user@example.com   string
4  string       0       0  user@example.com   string
5  string       0       0  user@example.com   string
6     sss     123     123  qwer@example.com  dddring

In [22]:
class Xmodel(BaseModel):
    n:PositiveInt|None=0
    c:int

In [23]:
bb = Xmodel(c=10)

In [24]:
bb

Xmodel(n=0, c=10)

In [25]:
cc = Xmodel(n=11,c=20)

In [26]:
cc

Xmodel(n=11, c=20)

In [27]:
dd = Xmodel(n=-1,c=0)

ValidationError: 1 validation error for Xmodel
n
  Input should be greater than 0 [type=greater_than, input_value=-1, input_type=int]
    For further information visit https://errors.pydantic.dev/2.8/v/greater_than

In [28]:
bb = pd.DataFrame(columns=['reg_id','ap','abp','bp','op','an','abn','bn','on'])

In [31]:
bb.to_csv('db/bloodbank_data.csv')

In [32]:
from enum import Enum

In [33]:
class ac(str,Enum):
    ADD:'add'
    REMOVE:'remove'

In [35]:
act = ac(REMOVE='remove')

TypeError: EnumType.__call__() got an unexpected keyword argument 'REMOVE'

In [38]:
ndf = pd.DataFrame(data=[[1,2,3]],columns=['a','b','c'])

In [39]:
ndf

a  b  c
0  1  2  3

In [40]:
ndf['a']=ndf['a']+10

In [41]:
ndf

a  b  c
0  11  2  3

In [54]:
temp =ndf.iloc[0].values

In [55]:
ntmp = [11,22,33]

In [56]:
temp+ntmp

array([22, 24, 36])

In [52]:
for i in ndf.loc[0]:
    print(i)
    

11
2
3


In [60]:
xx ={'reg':12,
     'ap':1,
     'qq':2}

In [61]:
xx.values()

dict_values([12, 1, 2])

In [63]:
ndf.iloc[0]=xx.values()

In [64]:
ndf

a  b  c
0  12  1  2

In [65]:
from schema import Blood_bank_update

In [66]:
bbx=Blood_bank_update(reg_id=11,ap=1,abp=1,bp=1,op=1,an=1,abn=1,bn=1,on=1)

In [68]:
bbx

Blood_bank_update(reg_id=11, ap=1, abp=1, bp=1, op=1, an=1, abn=1, bn=1, on=1)

In [69]:
bbxd = bbx.model_dump()

In [70]:
bbxd

{'reg_id': 11,
 'ap': 1,
 'abp': 1,
 'bp': 1,
 'op': 1,
 'an': 1,
 'abn': 1,
 'bn': 1,
 'on': 1}

In [84]:
bdf = pd.read_csv('db/bloodbank_data.csv')

In [74]:
bdf

Empty DataFrame
Columns: [reg_id, ap, abp, bp, op, an, abn, bn, on]
Index: []

In [75]:
newdf = pd.DataFrame([bbxd])

In [77]:
newdf

reg_id  ap  abp  bp  op  an  abn  bn  on
0      11   1    1   1   1   1    1   1   1

In [78]:
dff = pd.concat([bdf,newdf],ignore_index=True)

In [79]:
dff

reg_id ap abp bp op an abn bn on
0     11  1   1  1  1  1   1  1  1

In [82]:
if bbxd['reg_id'] in dff['reg_id']:
    print('id')
else:
    print('dd')    

dd


In [83]:
dff['reg_id']

0    11
Name: reg_id, dtype: object

In [85]:
bdf

Unnamed: 0  reg_id  ap  abp  bp  op  an  abn  bn  on
0           0      10  10   10  10  10  10   10  10  10

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('db/bloodbank_data.csv')

In [3]:
df

Unnamed: 0  reg_id  ap  abp  bp  op  an  abn  bn  on
0           0      10  10   10  10  10  10   10  10  10

In [4]:
db = pd.DataFrame(columns=['reg_id','ap','abp','bp','op','an','abn','bn','on'])

In [8]:
db

Empty DataFrame
Columns: [reg_id, ap, abp, bp, op, an, abn, bn, on]
Index: []

In [9]:
ndf = pd.read_csv('db/db.csv')

In [10]:
ndf

name  reg_id   phone             email    place
0   nisar    1234  123456   nsr@example.com      vly
1     nis  234234    2345    ns@example.com      vly
2      as     123     344    ab@example.com      acv
3  string       0       0  user@example.com   string
4  string       0       0  user@example.com   string
5  string       0       0  user@example.com   string
6     sss     123     123  qwer@example.com  dddring

In [26]:
if 'nis' in ndf['name'].values:
    print('no')
else:

    print('re')    

no


In [29]:
df=pd.read_csv('db/nbb.csv')

In [30]:
df

Empty DataFrame
Columns: [reg_id, ap, abp, bp, op, an, abn, bn, on]
Index: []

In [22]:
list(ndf['name'])

['nisar', 'nis', 'as', 'string', 'string', 'string', 'sss']

In [13]:
ndf['reg_id']

0      1234
1    234234
2       123
3         0
4         0
5         0
6       123
Name: reg_id, dtype: int64

In [34]:
if 'name' in df['reg_id'].values:
    print('ok')
else:
    print('nd')    

nd


In [44]:
from schema import Hospital,BBaction

In [36]:
x = Hospital(name='df',reg_id=12,phone=12,email='a@gmail.com',place='df')

In [38]:
type(x)

schemas.schema.Hospital

In [40]:
y=x.model_dump()

In [43]:
y['reg_id']

12

In [47]:
BBaction.ADD

<BBaction.ADD: 'add'>

In [54]:
nbb = pd.read_csv('db/nbb.csv')

In [55]:
nbb

reg_id  ap  abp  bp  op  an  abn  bn  on
0      10  10   10  10  10  10   10  10  10
1      20  10   10  10  10  10   10  10  10
2      30  10   10  10  10  10   10  10  10
3      40  10   10  10  10  10   10  10  10

In [93]:
nv=nbb.iloc[:,1:][nbb['reg_id']==10].values

In [94]:
nv

array([[10, 10, 10, 10, 10, 10, 10, 10]])

In [96]:
xv=[2,2,2,2,2,2,2,2]

In [97]:
vv = nv+xv

In [98]:
vv

array([[12, 12, 12, 12, 12, 12, 12, 12]])

In [100]:
nbb.iloc[:,1:][nbb['reg_id']==10]=vv


/tmp/ipykernel_16010/4183309312.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  nbb.iloc[:,1:][nbb['reg_id']==10]=vv
/tmp/ipykernel_16010/4183309312.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a D

In [101]:
nbb

reg_id  ap  abp  bp  op  an  abn  bn  on
0      10  12   12  12  12  12   12  12  12
1      20  10   10  10  10  10   10  10  10
2      30  10   10  10  10  10   10  10  10
3      40  10   10  10  10  10   10  10  10

In [109]:
nbb[nbb['reg_id']==10][]

reg_id  ap  abp  bp  op  an  abn  bn  on
0      10  12   12  12  12  12   12  12  12

In [112]:
nbb[1:][nbb['reg_id']==20]

/tmp/ipykernel_16010/3081486804.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  nbb[1:][nbb['reg_id']==20]


reg_id  ap  abp  bp  op  an  abn  bn  on
1      20  10   10  10  10  10   10  10  10

In [117]:
nbb[nbb[1:][nbb['reg_id']==20]]

/tmp/ipykernel_16010/46806576.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  nbb[nbb[1:][nbb['reg_id']==20]]


ValueError: Boolean array expected for the condition, not object

In [121]:
nbb.query('reg_id == 20 and ')

reg_id  ap  abp  bp  op  an  abn  bn  on
1      20  10   10  10  10  10   10  10  10

In [126]:
nbb.iloc[:,1:][nbb['reg_id']==20]

ap  abp  bp  op  an  abn  bn  on
1  10   10  10  10  10   10  10  10

In [ ]:
nbb[re]

In [134]:
vv


array([[12, 12, 12, 12, 12, 12, 12, 12]])

In [147]:
xv

[2, 2, 2, 2, 2, 2, 2, 2]

In [143]:
nv[:]

array([[10, 10, 10, 10, 10, 10, 10, 10]])

In [149]:
aa=[1,2,3]
bb=[4,4,5]


In [150]:
cc=aa+bb

In [151]:
cc

[1, 2, 3, 4, 4, 5]

In [127]:
nbb.loc[nbb['reg_id']==20]

reg_id  ap  abp  bp  op  an  abn  bn  on
1      20  10   10  10  10  10   10  10  10

In [155]:
nbb.loc[nbb['reg_id']==1]

reg_id  ap  abp  bp  op  an  abn  bn  on
1       1   1    1   1   1   1    1   1   1

In [156]:
import numpy as np

In [153]:
nbb

reg_id  ap  abp  bp  op  an  abn  bn  on
0      10  12   12  12  12  12   12  12  12
1       1   1    1   1   1   1    1   1   1
2      30  10   10  10  10  10   10  10  10
3      40  10   10  10  10  10   10  10  10

In [157]:
zz=np.array(xv)

In [158]:
zz

array([2, 2, 2, 2, 2, 2, 2, 2])

In [168]:
old_val=nbb.iloc[:,1:][nbb.reg_id==1].values.flatten()

In [170]:
old_val

array([1, 1, 1, 1, 1, 1, 1, 1])

In [171]:
zz

array([2, 2, 2, 2, 2, 2, 2, 2])

In [172]:
up = old_val+zz

In [173]:
up

array([3, 3, 3, 3, 3, 3, 3, 3])

In [178]:
nbb.columns[1:]

Index(['ap', 'abp', 'bp', 'op', 'an', 'abn', 'bn', 'on'], dtype='object')

In [187]:
nbb.loc[nbb.reg_id==1,nbb.columns[1:]].values.flatten()

array([3, 3, 3, 3, 3, 3, 3, 3])

In [183]:
nbb

reg_id  ap  abp  bp  op  an  abn  bn  on
0      10  12   12  12  12  12   12  12  12
1       1   3    3   3   3   3    3   3   3
2      30  10   10  10  10  10   10  10  10
3      40  10   10  10  10  10   10  10  10

In [188]:
nbb

reg_id  ap  abp  bp  op  an  abn  bn  on
0      10  12   12  12  12  12   12  12  12
1       1   3    3   3   3   3    3   3   3
2      30  10   10  10  10  10   10  10  10
3      40  10   10  10  10  10   10  10  10

In [189]:
newv={
  "reg_id": 40,
  "ap": 10,
  "abp": 10,
  "bp": 10,
  "op": 10,
  "an": 10,
  "abn": 10,
  "bn": 10,
  "on": 10
}

In [207]:
nz=newv.items()

In [217]:
list(newv.values())

[40, 10, 10, 10, 10, 10, 10, 10, 10]

In [200]:
vls

dict_values([40, 10, 10, 10, 10, 10, 10, 10, 10])

In [218]:
vvv=np.array(list(newv.values()))

In [219]:
vvv

array([40, 10, 10, 10, 10, 10, 10, 10, 10])

In [228]:
ccc= pd.read_csv('db/nbb.csv')

In [229]:
ccc

reg_id  ap  abp   bp  op  an  abn  bn  on
0    10.0  10   10   10  10  10   10  10  10
1    20.0  10   10   10  10  10   10  10  10
2    30.0  10   10   10  10  10   10  10  10
3    40.0  20   20   20  20  20   20  20  20
4     NaN  10   10   10  10  10   10  10  10
5    50.0  20   20  110  20  20   20  20  20
6    60.0  10   10  100  10  10   10  10  10

In [1]:
import pandas as pd

In [2]:
df= pd.DataFrame(columns=['name','age','blood_type','phone','place'])

In [5]:
df.to_csv('db/individual.csv',index=False)

In [10]:
xx =pd.read_csv('db/individual.csv')

In [11]:
xx

name  age blood_type  phone place
0   ab   13         bp  12342    kv
1   ab   13         bp    342    kv

In [ ]:
def dec(fun):
    def wrapper(a,b):
       x= fun(a,b)
       return x
    return wrapper   

In [7]:
def dec(a):
    print("start")
    a()
    print('end')
 
def n():
    print("work")    

In [12]:
@dec
def n():
    print("work")

start
work
end


In [13]:
def dec(fun):
    def wrapper(a,b):
        x = a+b
        y = a-b
        ans = fun(x,y)
        return ans
    return wrapper
    

In [14]:
@dec
def x(a,b):
    return a+b

In [15]:
x(2,1)

4

SyntaxError: invalid syntax (3370496669.py, line 2)

In [17]:
from pydantic import BaseModel
from enum import Enum

In [18]:
class Blood(Enum):
    A_positive = 1

In [19]:
x = Blood

In [27]:
class Blood_types(Enum):
    A_positive = 'a_positive'
    AB_positive = 'ab_positive'
    B_positive = 'b_positive'
    O_positive = '0_positive'
    A_negative = 'a_negative'
    AB_negative = 'ab_negative'
    B_negative = 'b_negative'
    O_negative = 'o_negative'    

In [28]:
class Blood(BaseModel):
    blood_type:Blood_types

In [36]:
x= Blood(blood_type='apositive')

ValidationError: 1 validation error for Blood
blood_type
  Input should be 'a_positive', 'ab_positive', 'b_positive', '0_positive', 'a_negative', 'ab_negative', 'b_negative' or 'o_negative' [type=enum, input_value='apositive', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/enum

In [35]:
x.blood_type.value

'a_positive'

In [41]:
from typing import Literal

In [37]:
class B_types(str,Enum):
    A = 'A'
    AB = 'AB'
    B = 'B'
    O = 'O'

In [59]:
class btype(BaseModel):
    antigen: str=B_types
    rh_factor: str=Literal['positive','negative']

In [62]:
B_types.A.value

'A'

In [60]:
x= btype(antigen=B_types.A,rh_factor='positive')

In [61]:
x

btype(antigen='A', rh_factor='positive')

In [64]:
class Individual(BaseModel):
    name:str
    age:int
    blood_type:btype
    phone:int
    place:str
    

In [65]:
nn = Individual(name='a',age=1,blood_type=['A','positive'],phone=2,place='w')

ValidationError: 1 validation error for Individual
blood_type
  Input should be a valid dictionary or instance of btype [type=model_type, input_value=['A', 'positive'], input_type=list]
    For further information visit https://errors.pydantic.dev/2.8/v/model_type

In [66]:
class Blood_group(str,Enum):
    Ap = 'A+ve'
    ABp = 'AB+ve'
    Bp = 'B+ve'
    Op = 'O+ve'
    An =  'A-ve'
    ABn  ='AB-ve'
    Bn  = 'B-ve'
    On  = 'O-ve'
    

In [72]:
    
class Individual(BaseModel):
    name:str
    age:int
    blood_type:str=Blood_group

In [73]:
zz = Individual(name='q',age=1,blood_type=Blood_group.ABn)

In [74]:
zz

Individual(name='q', age=1, blood_type='AB-ve')

In [1]:
import psycopg2

In [3]:
try:
    conn = psycopg2.connect(host='localhost',database='my_pgdb',port='5432',user='postgres',password='arkt123')
except:
    print('not connected')    

In [13]:
db = conn.cursor()

In [5]:
db.execute("""
           select * from hospitals
           """)

In [6]:
df = db.fetchall()

In [7]:
df

[]

In [14]:
emp = db.execute("""
                 INSERT INTO EMPLOYEE (empid,name,dept) VALUES (1,'A','F')
                 """)

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block


In [15]:
def configure():
   try: 
     conn = psycopg2.connect(host='localhost',database='my_pgdb',port='5432',user='postgres',password='arkt123')
     return conn
   except:
       print('failed')  

SyntaxError: incomplete input (1376631244.py, line 3)

In [21]:
def add_profile(profile:tuple):
    
    command = "INSERT INTO employee (empid,name,dept) VALUES (%s,%s,%s)"
    try :
        conn = psycopg2.connect(host='localhost',database='my_pgdb',port='5432',user='postgres',password='arkt123')
        cur = conn.cursor()
        cur.execute(command,profile)
        conn.commit()
    except (Exception, psycopg2.DatabaseError) as error:
        print(error)
    finally:
        conn.close()

In [22]:
add_profile((23,'ab','it'))

In [1]:
x= {'as':'df','w':'ee','gg':'ww'}

In [2]:
x

{'as': 'df', 'w': 'ee', 'gg': 'ww'}

In [7]:
x.keys()

dict_keys(['as', 'w', 'gg'])

In [33]:
val=iter(tuple(x.values()))

In [1]:
aa = 0123

SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers (1475944767.py, line 1)

In [32]:
next(val)

'df'

In [ ]:
g = 10

In [28]:
next(val)

StopIteration: 

In [38]:
fld = str(tuple(x.values()))

In [39]:
fld

"('df', 'ee', 'ww')"

In [42]:
h =f"INSERT INOT hospitals {fld}"

In [43]:
h

"INSERT INOT hospitals ('df', 'ee', 'ww')"

In [ ]:
for i in 

In [44]:
INSERT ="INSERT"
INTO ="INTO"
table_name = ""
fields = "(%s)"

In [ ]:
fields = fields.format()

In [45]:
from schema import Individual

In [46]:
zz = Individual(name='a',age='2',blood_type='a+ve',phone=23,pin_code=12,place='df')

In [54]:
zz

Individual(name='a', age=2, blood_type='a+ve', phone=23, place='df', pin_code=12)

In [ ]:
cc = "sdfsdf (%s)"

In [56]:
zz_val = zz.model_dump()

In [63]:
param = tuple(zz_val.values())

In [64]:
param

('a', 2, 'a+ve', 23, 'df', 12)

In [1]:
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

db_url ="postgresql://postgres:arkt123@localhost/my_pgdb"

engine = create_engine(db_url)
session_local = sessionmaker(autoflush=False,autocommit =False,bind=engine)

In [ ]:
from sqlalchemy.orm import Session

In [8]:
def inner(x):
    if x==1:
        return True

In [9]:
def fun(val):
    ans = inner(int(val))
    
    if ans:
        print('dd')
    else:
        print('error')

In [11]:
fun(2)

error


In [1]:
from schema import Blood_bank_update

In [2]:
x = Blood_bank_update(reg_id=123123)

In [9]:

val = x.model_dump()

In [12]:
val.values()


dict_values([123123, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
l =[    32123,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0
  ]

In [14]:
l

[32123, 0, 0, 0, 0, 0, 0, 0, 0]

In [15]:
from schema import Blood_bank_update

In [21]:
bb_l = Blood_bank_update(* *l)

TypeError: schema.Blood_bank_update() argument after ** must be a mapping, not list

In [24]:
from crud import get_bloodbank
from schema import Blood_bank_update

In [25]:
b= Blood_bank_update(reg_id=32123,abn=29,bp=10)

In [26]:
b

Blood_bank_update(reg_id=32123, ap=0, abp=0, bp=10, op=0, an=0, abn=29, bn=0, on=0)

In [27]:
x= get_bloodbank(int(32123))

In [31]:
type(x)

psycopg2.extras.RealDictRow

In [32]:
x

RealDictRow([('reg_id', 32123),
             ('a_pos', 0),
             ('ab_pos', 0),
             ('b_pos', 0),
             ('o_pos', 0),
             ('a_neg', 0),
             ('ab_neg', 0),
             ('b_neg', 0),
             ('o_neg', 0)])

In [33]:
nb = Blood_bank_update(**x)

In [34]:
nb

Blood_bank_update(reg_id=32123, ap=0, abp=0, bp=0, op=0, an=0, abn=0, bn=0, on=0)

In [39]:
xx=x.copy()

In [38]:
xx

RealDictRow([('reg_id', 32123),
             ('a_pos', 0),
             ('ab_pos', 0),
             ('b_pos', 0),
             ('o_pos', 0),
             ('a_neg', 0),
             ('ab_neg', 0),
             ('b_neg', 0),
             ('o_neg', 0)])

In [44]:
list(x.values())


[32123, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
nn = Blood_bank_update(re)

In [72]:
from schema import Blood_bank_update


In [73]:
zz = Blood_bank_update(reg_id=321232,ap=10,op=2,bn=3)

In [74]:
zz

Blood_bank_update(reg_id=321232, ap=10, abp=0, bp=0, op=2, an=0, abn=0, bn=3, on=0)

In [68]:
type(zz.on)

int

In [75]:
aa = Blood_bank_update(reg_id=321232,ap=10,abp=3,bp=3,op=2,bn=3,on=5)

In [76]:
aa

Blood_bank_update(reg_id=321232, ap=10, abp=3, bp=3, op=2, an=0, abn=0, bn=3, on=5)

In [78]:
q=zz+aa

TypeError: unsupported operand type(s) for +: 'Blood_bank_update' and 'Blood_bank_update'

In [1]:
from pydantic import BaseModel

In [4]:
class ob(BaseModel):
    id : int
    name : str
    count : int
    
    def __add__(self,other):
        return ob(id=self.id,name=self.name,count=self.count+other.count)

In [5]:
aa = ob(id=123,name='asd',count=22)

In [6]:
aa

ob(id=123, name='asd', count=22)

In [7]:
bb = ob(id=123,name='asd',count=10) 

In [8]:
bb

ob(id=123, name='asd', count=10)

In [9]:
aa

ob(id=123, name='asd', count=22)

In [11]:
cc=aa+bb

In [12]:
cc

ob(id=123, name='asd', count=32)

In [14]:
from pydantic import PositiveInt

In [15]:
class Blood_bank_update(BaseModel):
    reg_id:int
    ap  :PositiveInt|int=0
    abp :PositiveInt|int=0
    bp  :PositiveInt|int=0
    op  :PositiveInt|int=0
    an  :PositiveInt|int=0
    abn :PositiveInt|int=0
    bn  :PositiveInt|int=0
    on  :PositiveInt|int=0
   
    def __add__(self,other):
        if isinstance(other,Blood_bank_update):
            
            return Blood_bank_update(reg_id=self.reg_id,
                                     ap=self.ap+other.ap,
                                     abp=self.abp+other.abp,
                                     bp=self.bp+other.bp,
                                     op=self.op+other.op,
                                     an=self.an+other.an,
                                     abn=self.abn+other.abn,
                                     bn=self.bn+other.bn,
                                     on=self.on+other.on)
        return NotImplemented

In [16]:
b1 = Blood_bank_update(reg_id=123,abn=34,on=3,bn=4)

In [17]:
b1

Blood_bank_update(reg_id=123, ap=0, abp=0, bp=0, op=0, an=0, abn=34, bn=4, on=3)

In [20]:
b2 = Blood_bank_update(reg_id=123,abn=111)

In [21]:
b2

Blood_bank_update(reg_id=123, ap=0, abp=0, bp=0, op=0, an=0, abn=111, bn=0, on=0)

In [22]:
b1+b2

Blood_bank_update(reg_id=123, ap=0, abp=0, bp=0, op=0, an=0, abn=145, bn=4, on=3)

In [1]:
q = (1,2,3)

In [12]:
q[1:]

(2, 3)

In [3]:
from crud import get_bloodbank

In [4]:
x  = get_bloodbank(32123)

In [5]:
x.dic()

AttributeError: 'dict' object has no attribute 'dic'

In [17]:
x= dic(x)

NameError: name 'dic' is not defined

In [6]:
x

{'reg_id': 32123,
 'a_pos': 0,
 'ab_pos': 0,
 'b_pos': 0,
 'o_pos': 0,
 'a_neg': 0,
 'ab_neg': 0,
 'b_neg': 0,
 'o_neg': 0}

In [23]:
from typing import Dict

In [7]:
x = dict(x)

In [8]:
x

{'reg_id': 32123,
 'a_pos': 0,
 'ab_pos': 0,
 'b_pos': 0,
 'o_pos': 0,
 'a_neg': 0,
 'ab_neg': 0,
 'b_neg': 0,
 'o_neg': 0}

In [9]:
x.pop('reg_id')

32123

In [10]:
x

{'a_pos': 0,
 'ab_pos': 0,
 'b_pos': 0,
 'o_pos': 0,
 'a_neg': 0,
 'ab_neg': 0,
 'b_neg': 0,
 'o_neg': 0}

In [11]:
from schema import Blood_units

In [12]:
aa = Blood_units(**x)

In [13]:
aa

Blood_units(ap=0, abp=0, bp=0, op=0, an=0, abn=0, bn=0, on=0)

In [30]:
q = (1,2,3,4)

In [31]:
q[1:]

(2, 3, 4)

In [36]:
zz = q[1:],q[0]

In [37]:
zz

((2, 3, 4), 1)

In [15]:
aa_un  = aa.model_dump()

In [18]:
aa_un

{'ap': 0, 'abp': 0, 'bp': 0, 'op': 0, 'an': 0, 'abn': 0, 'bn': 0, 'on': 0}

In [23]:
val = list(aa_un.values())

In [24]:
val

[0, 0, 0, 0, 0, 0, 0, 0]

In [29]:
cc=aa.__dict__

In [31]:
type(cc)

dict

In [32]:
cc

{'ap': 0, 'abp': 0, 'bp': 0, 'op': 0, 'an': 0, 'abn': 0, 'bn': 0, 'on': 0}

In [45]:
for k1,v1,k2,v2 in zip(aa.__dict__.items(),aa.__dict__.items()):
    print(k1,v1)
    print(k2,v2)
        

ValueError: not enough values to unpack (expected 4, got 2)

In [48]:
list(aa.__dict__.values())

[0, 0, 0, 0, 0, 0, 0, 0]

In [1]:
from schema import Blood_units

In [2]:
ww = Blood_units(a_pos=10,ab_pos=10)

In [3]:
ww

Blood_units(a_pos=10, ab_pos=10, b_pos=0, o_pos=0, a_neg=0, ab_neg=0, b_neg=0, o_neg=0)

In [4]:
qq = Blood_units(a_pos=10,ab_pos =11,b_pos=10)

In [5]:
qq

Blood_units(a_pos=10, ab_pos=11, b_pos=10, o_pos=0, a_neg=0, ab_neg=0, b_neg=0, o_neg=0)

In [6]:
ww+qq

Blood_units(a_pos=20, ab_pos=21, b_pos=10, o_pos=0, a_neg=0, ab_neg=0, b_neg=0, o_neg=0)

In [7]:
ww

Blood_units(a_pos=10, ab_pos=10, b_pos=0, o_pos=0, a_neg=0, ab_neg=0, b_neg=0, o_neg=0)

In [8]:
qq

Blood_units(a_pos=10, ab_pos=11, b_pos=10, o_pos=0, a_neg=0, ab_neg=0, b_neg=0, o_neg=0)

In [9]:
ww-qq

Blood_units(a_pos=0, ab_pos=-1, b_pos=-10, o_pos=0, a_neg=0, ab_neg=0, b_neg=0, o_neg=0)

In [10]:
qq

Blood_units(a_pos=10, ab_pos=11, b_pos=10, o_pos=0, a_neg=0, ab_neg=0, b_neg=0, o_neg=0)

In [13]:
qq.__getattribute__('ab_pos')

11

In [17]:
from pydantic import BaseModel

In [21]:
class ch(BaseModel):
    a:int =10
    b:int = 5
    c:int = 0
    
    def g(self):
        for fields in self.__fields__:
            print(fields)

In [22]:
chval = ch()

In [23]:
chval.g()

a
b
c


In [26]:
for i in chval.__fields__:
    print(i)

a
b
c


In [27]:
ch2 = ch(a=5,b=6,c=2)

In [29]:
ch2,chval

(ch(a=5, b=6, c=2), ch(a=10, b=5, c=0))

In [37]:
for i in chval.__fields__:
    print(i)
    print(chval.__getattribute__(i))

a
10
b
5
c
0


In [35]:
chval

TypeError: 'ch' object is not subscriptable

In [41]:
chval

ch(a=10, b=5, c=0)

In [42]:
ch2

ch(a=5, b=6, c=2)

In [53]:
non_operable={}
operable = {}
for i in chval.__fields__:
    if  chval.__getattribute__(i) < ch2.__getattribute__(i):
        non_operable[i] = ch2.__getattribute__(i)
    else:
        
        operable[i] = chval.__getattribute__(i) - ch2.__getattribute__(i)
if non_operable:
        print(non_operable)
        raise ValueError('new value is more then existing value')

{'b': 6, 'c': 2}


ValueError: new value is more then existing value

In [52]:
non_operable

{'b': 6, 'c': 2}

In [43]:
operable

{'a': 5}

In [65]:
ch2

ch(a=5, b=6, c=2)

In [55]:
for i in ch2.model_fields:
    print(i)


a
b
c


In [64]:
op ={}
for i in ch2.model_fields_set:
    print(i)
    op[i] = ch2.__getattribute__(i)

a
c
b


In [63]:
op

{'a': 5, 'c': 2, 'b': 6}

In [69]:
opp = {"a":1}

In [70]:
if opp: 
    print("t")
else:
    print('a')

t


In [1]:
import os

In [13]:
os.getcwd()

'/home/abdurahiman/Desktop/fastapi_tut'

In [15]:
os.getcwdb()

b'/home/abdurahiman/Desktop/fastapi_tut'

In [16]:
os.getenv('user')

'postgres'

In [17]:
os.environ['new_val'] = 'osenv'

In [20]:
pt = os.path.join(os.path.dirname())

AttributeError: 'str' object has no attribute '__file__'